### ISSUE TITLE
List package at at https://gap-packages.github.io/ 

### ISSUE THREAD

**Issue by olexandr-konovalov** [MathieuDutSik/Satisfiability#1]
We maintain a list of GAP packages with their public repositories at https://gap-packages.github.io/ - would you like this package to be listed there? It's not limited to packages redistributed with GAP - the aim is to list all packages independently of their status. This will help other GAP users and developers to find them.

**Comment by MathieuDutSik** [comment]
Hi Alexander,

Yes you can put this software on this web page.
I am working on making my GAP code available to
other users and this is big work, bigger than I expected.
My stumbling point on Satisfiability is writing manual
before submission.

We had been in communication before about submitting
the polyhedral package. And so, I should explain you the
current situation. This is actually a big beast of a problem
since I have 86000 lines of code and this cannot be submitted
as is and has to be cleaned up and broken up in smaller
pieces.

Meanwhile, I am working in coding all that in C++ which
I find better for high performance computing which is the
end objective of most of my work. This code is completely
accessible. See https://github.com/MathieuDutSik/polyhedral_common

For a long time, the stumbling point was that I did not
have the equivalent of GAP permutation group algorithms.
This has now been mostly addressed with
https://github.com/MathieuDutSik/permutalib
which is a very very similar reimplementation of the
algorithms of GAP for permutation groups.

Best wishes,

  Mathieu

**Comment by olexandr-konovalov** [comment]
Thanks, done in https://github.com/gap-packages/gap-packages.github.io/commit/6456c40b6b5d08be3651f2f886e6d00e3ee2c085.

For writing documentation, the AutoDoc package may be helpful: https://gap-packages.github.io/AutoDoc/ - you need to know something about GAPDoc, but it saves you from writing raw XML. 

Thanks for the other details, that's interesting to know!
